<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Getting Started In PHP</title>
</head>
<body>
<!--Write the traditional greeting-->
<?php echo "<h1>Hello World!</h1>"; ?>

<hr>
<!--Scripting rules-->
<h2>Scripting rules</h2>
<p style="color: red">Ignored by PHP and displayed by the browser</p>

<?php
// PHP code here — executed by the server
echo "Hello, this text was generated by PHP!";
?>

<p style="color: red">Also ignored by PHP and displayed by the browser</p>

<hr>
<!--Short Echo Tags-->
<h2>Short Echo Tags</h2>
<?= "This text printed using \"Short Echo Tags\"" ?>

<hr>
<!--Conditional Output Tags-->
<h2>Conditional Output Tags</h2>
<?php $hour = date("H"); ?>
<?php if ($hour < 12): ?>
    <p>Good morning!</p>
<?php else: ?>
    <p>Good afternoon!</p>
<?php endif; ?>

<hr>
<!--Statement Rules — The Semicolon-->
<h2>Statement Rules — The Semicolon</h2>
<?php
echo "First statement <br>";
echo "Second statement <br>";
?>
<?php
$name = "Alice";
$age = 30;
echo "Name: " . $name;
echo "<br>";
echo "Age: " . $age;
echo "<br>";
?>
<h4>When to omit semi-colon in the last line</h4>
<?php
echo "First statement -> semicolon a must here <br>";
echo "Last statement —> semicolon optional here <br>"
?>
<h4>When to omit semi-colon in the first line</h4>
<?php echo "First statement -> semicolon omitted — valid <br>" ?>        <!-- semicolon omitted — valid -->
<?php echo "Last statement -> semicolon included — also valid"; ?>       <!-- semicolon included — also valid -->
</body>
</html>